### PR TITLE
Fix original limits being exported in MB

### LINKED ISSUE #151: Original memory requests/limits values are incorrect on the grafana dashboard
**Describe the bug**
Original memory requests/limits values are incorrect on the grafana dashboard

**To Reproduce**
Steps to reproduce:
- Deploy kruize using the below command:
./deploy.sh -ac docker -i chandra25ms/kruize:0.6.6 

- Deploy acmeair or any application by specifying cpu/memory requests
 memory: 500M
 cpu: 2
 limits:
 memory: 1024M
 cpu: 3

I have attached the screenshot, the values for acmeair shown are 500B and 1kB instead of 500M and 1024M

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Kubernetes Environment Minikube
**Additional context**

### PR DESCRIPTION
**Pull request by ShishirH**
Fixes #151 

In the recent change, all values were being saved in MB. However, the Kruize grafana dashboard expects values in bytes. Reverting back the change to MB for original limits and requests.

Also added a couple of null checks.

Signed-off-by: Shishir Halaharvi <shihala1@in.ibm.com>

### CODE REVIEW

File: src/main/java/com/kruize/environment/docker/DockerEnvImpl.java [hunk 1]
```diff
@@ -256,7 +256,7 @@ private MetricsImpl getMetrics(JsonElement container) throws NullPointerExceptio
         }
 
         if (container.getAsJsonObject().has("cpu_limit")) {
-            containerMetrics.setOriginalMemoryLimit(container.getAsJsonObject().get("cpu_limit").getAsDouble());
+            containerMetrics.setOriginalCpuLimit(container.getAsJsonObject().get("cpu_limit").getAsDouble());
```
Comment (ShishirH) [inline src/main/java/com/kruize/environment/docker/DockerEnvImpl.java:259]: @dinogun @chandrams Found out what was causing original memory limit not showing up for docker on the dashboard.

The wrong setter is being called, `setOriginalMemoryLimit` instead of `setOriginalCpuLimit`, and it has been that way since Docker support was added in the PR https://github.com/kruize/kruize/commit/64b223fb296915cdb2dce01ed8203286c704c28b#diff-f2f941ba783eebc51fbb5e439a5a0bba

This was causing the changes to be overwritten immediately, and the dashboard would stop showing the memory limits.
I ran petclinic using `docker run --memory="512M" with this change, and it showed up on the dashboard
